return {
	"ibhagwan/fzf-lua",
	keys = {
		{
			"<leader>fv",
			function()
				require("fzf-lua").files({ cwd = vim.fn.stdpath("config") })
			end,
			desc = "Vim files",
			mode = { "n", "t" },
		},
		-- {
		-- 	"<leader>ff",
		-- 	function()
		-- 		require("fzf-lua").files()
		-- 	end,
		-- 	desc = "Find files",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fb",
		-- 	function()
		-- 		require("fzf-lua").buffers()
		-- 	end,
		-- 	desc = "Find buffers",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fo",
		-- 	function()
		-- 		require("fzf-lua").oldfiles()
		-- 	end,
		-- 	desc = "Find files history",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fq",
		-- 	function()
		-- 		require("fzf-lua").quickfix()
		-- 	end,
		-- 	desc = "Find quickfix list",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fQ",
		-- 	function()
		-- 		require("fzf-lua").quickfix_stack()
		-- 	end,
		-- 	desc = "Find quickfix stack",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fl",
		-- 	function()
		-- 		require("fzf-lua").lines()
		-- 	end,
		-- 	desc = "Buffers lines",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fL",
		-- 	function()
		-- 		require("fzf-lua").blines()
		-- 	end,
		-- 	desc = "Current buffer lines",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>ft",
		-- 	function()
		-- 		require("fzf-lua").treesitter()
		-- 	end,
		-- 	desc = "Current buffer treesitter symbols",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fT",
		-- 	function()
		-- 		require("fzf-lua").tabs()
		-- 	end,
		-- 	desc = "Open tabs",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fa",
		-- 	function()
		-- 		require("fzf-lua").args()
		-- 	end,
		-- 	desc = "Argument list",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>fr",
		-- 	function()
		-- 		require("fzf-lua").resume()
		-- 	end,
		-- 	desc = "Resume",
		-- 	mode = { "n", "t" },
		-- },
		--
		-- -- Search
		-- {
		-- 	"<leader>sg",
		-- 	function()
		-- 		require("fzf-lua").live_grep()
		-- 	end,
		-- 	desc = "Live grep project",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>s/",
		-- 	function()
		-- 		require("fzf-lua").lgrep_curbuf()
		-- 	end,
		-- 	desc = "Live grep buffer",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>sw",
		-- 	function()
		-- 		require("fzf-lua").grep_cword()
		-- 	end,
		-- 	desc = "Find cursor word",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>sW",
		-- 	function()
		-- 		require("fzf-lua").grep_cWORD()
		-- 	end,
		-- 	desc = "Find cursor WORD",
		-- 	mode = { "n", "t" },
		-- },
		--
		-- -- Git
		-- {
		-- 	"<leader>gf",
		-- 	function()
		-- 		require("fzf-lua").git_files()
		-- 	end,
		-- 	desc = "Git files",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gs",
		-- 	function()
		-- 		require("fzf-lua").git_status()
		-- 	end,
		-- 	desc = "Git status",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gS",
		-- 	function()
		-- 		require("fzf-lua").git_stash()
		-- 	end,
		-- 	desc = "Git stash",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gd",
		-- 	function()
		-- 		require("fzf-lua").git_diff()
		-- 	end,
		-- 	desc = "Git diff",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gh",
		-- 	function()
		-- 		require("fzf-lua").git_hunks()
		-- 	end,
		-- 	desc = "Git hunks",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gc",
		-- 	function()
		-- 		require("fzf-lua").git_commits()
		-- 	end,
		-- 	desc = "Git commits",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gC",
		-- 	function()
		-- 		require("fzf-lua").git_bcommits()
		-- 	end,
		-- 	desc = "Git buffer commits",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gb",
		-- 	function()
		-- 		require("fzf-lua").git_blame()
		-- 	end,
		-- 	desc = "Git blame",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gB",
		-- 	function()
		-- 		require("fzf-lua").git_branches()
		-- 	end,
		-- 	desc = "Git branches",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>gt",
		-- 	function()
		-- 		require("fzf-lua").git_tags()
		-- 	end,
		-- 	desc = "Git tags",
		-- 	mode = { "n", "t" },
		-- },
		--
		-- -- LSP
		-- {
		-- 	"<leader>lR",
		-- 	function()
		-- 		require("fzf-lua").lsp_references()
		-- 	end,
		-- 	desc = "References",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lf",
		-- 	function()
		-- 		require("fzf-lua").lsp_definitions()
		-- 	end,
		-- 	desc = "Definitions",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lF",
		-- 	function()
		-- 		require("fzf-lua").lsp_declaratinos()
		-- 	end,
		-- 	desc = "Declarations",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lt",
		-- 	function()
		-- 		require("fzf-lua").lsp_typedefs()
		-- 	end,
		-- 	desc = "Type Definitions",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>li",
		-- 	function()
		-- 		require("fzf-lua").lsp_implementations()
		-- 	end,
		-- 	desc = "Implementations",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>ls",
		-- 	function()
		-- 		require("fzf-lua").lsp_document_symbols()
		-- 	end,
		-- 	desc = "Document Symbols",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lS",
		-- 	function()
		-- 		require("fzf-lua").lsp_workspace_symbols()
		-- 	end,
		-- 	desc = "Workspace Symbols",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lW",
		-- 	function()
		-- 		require("fzf-lua").lsp_live_workspace_symbols()
		-- 	end,
		-- 	desc = "Live Workspace Symbols",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lc",
		-- 	function()
		-- 		require("fzf-lua").lsp_incoming_calls()
		-- 	end,
		-- 	desc = "Incoming Calls",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lC",
		-- 	function()
		-- 		require("fzf-lua").lsp_outgoing_calls()
		-- 	end,
		-- 	desc = "Outgoing Calls",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>la",
		-- 	function()
		-- 		require("fzf-lua").lsp_code_actions()
		-- 	end,
		-- 	desc = "Code Actions",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lF",
		-- 	function()
		-- 		require("fzf-lua").lsp_finder()
		-- 	end,
		-- 	desc = "LSP Finder",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>ld",
		-- 	function()
		-- 		require("fzf-lua").lsp_document_diagnostics()
		-- 	end,
		-- 	desc = "Document Diagnostics",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lD",
		-- 	function()
		-- 		require("fzf-lua").lsp_workspace_diagnostics()
		-- 	end,
		-- 	desc = "Workspace Diagnostics",
		-- 	mode = { "n", "t" },
		-- },
		-- {
		-- 	"<leader>lW",
		-- 	function()
		-- 		require("fzf-lua").lsp_live_workspace_symbols()
		-- 	end,
		-- 	desc = "References",
		-- 	mode = { "n", "t" },
		-- },
	},
	config = function()
		require("fzf-lua").setup({
			winopts = {
				border = require("configs.ui").border("󰛔", "", ""),
			},
			preview = { border = require("configs.ui").border("", "", "") }, --  
		})
	end,
}
